### ISSUE TITLE
Separate PxlAnalyzer and MUSiC

### ISSUE THREAD

**Issue by tobias-pook** [Aachen-3A/PxlAnalyzer#12]
_From @serdweg on March 4, 2015 17:12_

At the moment the whole MUSiC code is always included even if you don't need it most of the time. It would therefore be useful to make a similar construction to SpecialAna, where if SpecialAna is not present a dummy version is used, otherwise the right one.

_Copied from original issue: Aachen-3A/PxlAnalyzer#8_

**Comment by padeken** [comment]
done
