### ISSUE TITLE
Uninitialized EventClasses created when Generator cuts used

### ISSUE THREAD

**Issue by tobias-pook** [Aachen-3A/PxlAnalyzer#12]
The EventClass factory may create uninitialized Event classes if Objects pass Reco but not Gen cuts.

**Comment by DebbieDuchardt** [comment]
AKC/                        CrabJobs@      Downloads/ 
kde_BU/           myProgs/         PickedEvents/  root/ 
talks/                timeCount.ods              Wohnungen/
bin/                        CSS_2014/      eventTables.txt 
kde_BU_02_03_14/  myScripts/       pictures/      scan@ 
Tandem/               Unpacked@                  workspace/
brainstorm/                 DAQ/           FSWTail@ 
kde_Old/          net_duchardt@    PlotMe/        Scanned@ 
Templates/            versuch_01_20140716-2.pdf  WprimeLimit/
classified@                 Desktop/       happyface_10-12-13.pdf 
LHC_GK/           papers/          Praktikum/     ScreenInfo.txt 
test_cookie.txt       versuch_01_20140716-5.pdf  x509up_u31101
CMSSW/                      Diplomarbeit/  inSync Share/ 
logo3inst/        pauls_vimrc      public/        shell_commands.txt 
TESTxml.txt           Videos/
C:\nppdf32Log\debuglog.txt  documents/     IT4Bayer/ 
merged@           PhotonFakeRate/  Reisekosten/   Skimming@ 
texmf/                vispa/
codingFun/                  dotfiles/      JabRef-2.6.jar 
mounts.log        photonSkimming@  repos/         SkimmingTools@ 
thunderbird-restore/  WINDOWS/
cowanLectures/              downloads/     joinedSkimmer/ 
MUSiC/            PhysicsTools/    reposits/      SusyWG@ 
timeCount_BU.ods      WINDOWS.OLD/

**Comment by serdweg** [comment]
Und ihr sagt mir man braucht genauere Beschreibungen der issues

**Comment by tobias-pook** [comment]
This issue was moved to Aachen-3A/PxlButcher#16
