### ISSUE TITLE
RECO_efficiency plots

### ISSUE THREAD

**Issue by ChSchuler** [Aachen-3A/PxlAnalyzer#14]
Unexpected structure in Reco-efficiency plots, for example eff_moun_reco_vs_pt. Changes of acceptance range delta_r_max (currently 0.25) do not solve the problem.

**Comment by padeken** [comment]
eff_moun_reco_vs_pt is in the RPV_Analyser right?

**Comment by serdweg** [comment]
yes, there is no real reason to do it at another place right?

**Comment by padeken** [comment]
No just want to know if there was some method that I didn't know about in the Analyser :-).
Is the problem also there for a non signal sample?

**Comment by serdweg** [comment]
I didn't have time yet to check it, but I will close and move the issue to the RPV analyzer

**Comment by padeken** [comment]
no I think it is a global problem

**Comment by tobias-pook** [comment]
This issue was moved to Aachen-3A/PxlButcher#18

**Comment by tobias-pook** [comment]
This issue was moved to Aachen-3A/PxlButcher#19
