### ISSUE TITLE
Adapt MUSiC to new EDM:Filter

### ISSUE THREAD

**Issue by tobias-pook** [Aachen-3A/PxlAnalyzer#15]
_From @tobias-pook on March 5, 2015 15:29_

Once Isuue https://github.com/Aachen-3A/PxlSkimmer/issues/5 is closed, we need to adapt MUSiC to the new filters.

_Copied from original issue: Aachen-3A/PxlAnalyzer#11_

**Comment by padeken** [comment]
done
