### ISSUE TITLE
Catch a keyboard interrupt and close the program usefull

### ISSUE THREAD

**Issue by serdweg** [Aachen-3A/PxlAnalyzer#3]
At the moment a Ctr+C stops the proggram, but the root file ist not usefull, therefore this should be modified.

**Comment by serdweg** [comment]
The feature is now included :-)
A Ctr+C is now catched and the analysis is properly closed.

**Comment by tobias-pook** [comment]
This issue was moved to Aachen-3A/PxlButcher#6
