### ISSUE TITLE
Fix that the validator runs in batch mode

### ISSUE THREAD

**Issue by serdweg** [Aachen-3A/PxlAnalyzer#6]
In some configurations the plots created by the validator are shown in the matplotlib browser, this function should be deactivated as all plots are already shown in the summary file.

**Comment by serdweg** [comment]
This should now be fixed by changing the matplotlib backend to 'AGG' for the validator

**Comment by tobias-pook** [comment]
This issue was moved to Aachen-3A/PxlButcher#10
