### ISSUE TITLE
Fix the memory leak in the PxlAnalyzer

### ISSUE THREAD

**Issue by tobias-pook** [Aachen-3A/PxlAnalyzer#9]
_From @serdweg on February 26, 2015 13:59_

At the moment about 100MB of memory usage are created every 60s run time, this should be fixed.

_Copied from original issue: Aachen-3A/PxlAnalyzer#5_

**Comment by padeken** [comment]
In the Wprime ana there is no memory leak so it shoud only be in the Validator!
