### ISSUE TITLE
Warnings from boost libraries

### ISSUE THREAD

**Issue by serdweg** [Aachen-3A/PxlAnalyzer#9]
I have tried to deactivate all boost libraries warnings to have usefull compilation output. This should all be now included in the dev branch. If somebody could just test this by pulling and calling make clean; make. If everything looks fine the issue can then be closed.

**Comment by tobias-pook** [comment]
Your fix seems to work. Thanks for the helpful contribution!

**Comment by tobias-pook** [comment]
This issue was moved to Aachen-3A/PxlButcher#13
